candy_mapper = {
    '3 musketeers candy bar': '3 Musketeers',
    '3 musketeers miniature bars': '3 Musketeers',
    '5 gum': '5 Gum',
    'airheads bites fruit 67': 'Airheads',
    'airheads white mystery': 'Airheads White Mystery',
    'airheads xtremes sweetly sour candy rainbow berry': 'Airheads Xtremes',
    'almond joy snack size bites': 'Almond Joy',
    'altoids curiously strong cinnamon mints': 'Altoids Cinnamon Mints',
    'bouquet of fruits valentine chocolate dipped strawberries': 'Chocolate Dipped Strawberries',
    'brachs candy corn': 'Candy Corn',
    'brookside dark chocolate acai blueberry flavors 51': 'Brookside Acai',
    'brookside dark chocolate pomegranate flavor 53': 'Brookside Pomegranate',
    'butterfinger candy bar': 'Butterfinger',
    'butterfinger minis': 'Butterfinger',
    'butterfinger peanut butter cups': 'Butterfinger Peanut Butter Cups',
    'butterfinger peanut butter cups minis': 'Butterfinger Peanut Butter Cups',
    'creme savers strawberries rolls': 'Creme Savers Strawberries Rolls',
    'demets turtles original': 'Turtles',
    'dove chocolate promises silky smooth almond dark chocolate': 'Dove Almond Dark Chocolate',
    'dove chocolate promises silky smooth milk chocolate': 'dove chocolate promises silky smooth milk chocolate',
    'dove chocolate promises silky smooth sea salt caramel dark chocolate': 'dove chocolate promises silky smooth sea salt caramel dark chocolate',
    'dove chocolate silky smooth dark chocolate large bar': 'dove chocolate silky smooth dark chocolate large bar',
    'dove chocolate silky smooth dark chocolate singles bar': 'dove chocolate silky smooth dark chocolate singles bar',
    'dove fruit chocolate': 'dove fruit chocolate',
    'ferrero collection fine assorted confections': 'Ferrero Assorted Confections',
    'ferrero rocher chocolate': 'Ferrero Rocher',
    'ghirardelli chocolate milk chocolate caramel square': 'ghirardelli chocolate milk chocolate caramel square',
    'ghirardelli gourmet milk sea salt escape': 'ghirardelli gourmet milk sea salt escape',
    'ghirardelli squares 60 peppermint bark': 'ghirardelli squares 60 peppermint bark',
    'godiva chocolates': 'godiva chocolates',
    'godiva gold ballotin with gold ribbon': 'godiva gold ballotin with gold ribbon',
    'haribo happy cola gummi candy': 'haribo happy cola gummi candy',
    'haribo juicy gold bears gummi candy': 'haribo juicy gold bears gummi candy',
    'haribo sour gold bears gummi candy': 'haribo sour gold bears gummi candy',
    'heath milk chocolate english toffee bar': 'heath milk chocolate english toffee bar',
    'heath milk chocolate english toffee bars': 'heath milk chocolate english toffee bars',
    'hersheys almond joy candy bar': 'hersheys almond joy candy bar',
    'hersheys cookies n creme candy bar': 'hersheys cookies n creme candy bar',
    'hersheys halloween snack size assortment': 'hersheys halloween snack size assortment',
    'hersheys kisses milk chocolate': 'hersheys kisses milk chocolate',
    'hersheys kisses milk chocolates with almonds': 'hersheys kisses milk chocolates with almonds',
    'hersheys milk chocolate bar': 'hersheys milk chocolate bar',
    'hersheys milk chocolate bar with almonds': 'hersheys milk chocolate bar with almonds',
    'hersheys natural unsweetened cocoa': 'hersheys natural unsweetened cocoa',
    'hersheys nuggets chocolate assortment 6': 'hersheys nuggets chocolate assortment 6',
    'hersheys nuggets milk chocolate with almonds': 'hersheys nuggets milk chocolate with almonds',
    'hersheys symphony milk chocolate with almonds and toffee bar': 'hersheys symphony milk chocolate with almonds and toffee bar',
    'hersheys variety pack assortment': 'hersheys variety pack assortment',
    'hersheys whoppers malted milk balls': 'hersheys whoppers malted milk balls',
    'hubba bubba bubbletape awesome original': 'hubba bubba bubbletape awesome original',
    'jelly belly the original gourmet jelly bean': 'jelly belly the original gourmet jelly bean',
    'jet puffed regular everyday marshmallows': 'jet puffed regular everyday marshmallows',
    'jet puffed stackermallows marshmallows': 'jet puffed stackermallows marshmallows',
    'jolly rancher hard candy original flavors assortment': 'jolly rancher hard candy original flavors assortment',
    'jolly rancher sugar free hard candy': 'jolly rancher sugar free hard candy',
    'juicy fruit gum': 'juicy fruit gum',
    'kirkland milk chocolate almonds': 'kirkland milk chocolate almonds',
    'kit kat big kat king size wafer bar': 'kit kat big kat king size wafer bar',
    'kit kat dark chocolate candy bar': 'kit kat dark chocolate candy bar',
    'kit kat minis crisp wafers in milk chocolate': 'kit kat minis crisp wafers in milk chocolate',
    'kit kat minis white chocolate candy': 'kit kat minis white chocolate candy',
    'kit kat orange and cream': 'kit kat orange and cream',
    'kraft vanilla caramels snack bags': 'kraft vanilla caramels snack bags',
    'life savers five flavor gummies': 'life savers five flavor gummies',
    'life savers holiday wint o green candy mints': 'life savers holiday wint o green candy mints',
    'lindt lindor milk chocolate truffles': 'lindt lindor milk chocolate truffles',
    'lindt lindor stracciatella chocolate': 'lindt lindor stracciatella chocolate',
    'lindt ultimate 8 flavor assortment lindor truffles': 'lindt ultimate 8 flavor assortment lindor truffles',
    'listerine pocketpaks oral care strips cool mint': 'listerine pocketpaks oral care strips cool mint',
    'mars candy fun size mix peanut and peanut butter lovers': 'mars candy fun size mix peanut and peanut butter lovers',
    'mike and ike sour licious zours': 'mike and ike sour licious zours',
    'milky way bar midnight dark': 'milky way bar midnight dark',
    'milky way candy bar': 'milky way candy bar',
    'milky way simply caramel bar': 'milky way simply caramel bar',
    'mms brand almond chocolate candies holiday blend': 'mms brand almond chocolate candies holiday blend',
    'mms brand dark chocolate candies holiday blend': 'mms brand dark chocolate candies holiday blend',
    'mms brand peanut butter chocolate candies holiday blend': 'mms brand peanut butter chocolate candies holiday blend',
    'mms milk chocolate candy 23': 'mms milk chocolate candy 23',
    'mms minis': 'mms minis',
    'mms peanut chocolate candy': 'mms peanut chocolate candy',
    'mounds candy bar': 'mounds candy bar',
    'nestle baby ruth bar': 'nestle baby ruth bar',
    'nestle butterfinger bites': 'nestle butterfinger bites',
    'nestle toll house semi sweet chocolate morsels': 'nestle toll house semi sweet chocolate morsels',
    'nestle toll house ultimatestm chocolate chip lovers cookie bar dough': 'nestle toll house ultimatestm chocolate chip lovers cookie bar dough',
    'oreo chocolate candy bar': 'oreo chocolate candy bar',
    'payday bar 185 oz bar 24 ct': 'payday bar 185 oz bar 24 ct',
    'pez candy': 'pez candy',
    'red vines original red': 'red vines original red',
    'reeses outrageous king size bar': 'reeses outrageous king size bar',
    'reeses peanut butter big cup': 'reeses peanut butter big cup',
    'reeses peanut butter bunny': 'reeses peanut butter bunny',
    'reeses peanut butter cup pumpkins milk chocolate': 'reeses peanut butter cup pumpkins milk chocolate',
    'reeses peanut butter cups miniatures 76': 'reeses peanut butter cups miniatures 76',
    'reeses peanut butter cups white': 'reeses peanut butter cups white',
    'reeses peanut butter egg': 'reeses peanut butter egg',
    'reeses peanut butter heart': 'reeses peanut butter heart',
    'reeses pieces peanut butter candy': 'reeses pieces peanut butter candy',
    'reeses reeses peanut butter trees': 'reeses reeses peanut butter trees',
    'reeses sticks wafer bars': 'reeses sticks wafer bars',
    'reeses white peanut butter cups': 'reeses white peanut butter cups',
    'reeses white peanut butter eggs': 'reeses white peanut butter eggs',
    'rolo candy': 'rolo candy',
    'skittles sour candy 55': 'skittles sour candy 55',
    'skittles sweets sours candy': 'skittles sweets sours candy',
    'skittles tropical candy': 'skittles tropical candy',
    'skittles wild berry candy': 'skittles wild berry candy',
    'snickers almond bar': 'snickers almond bar',
    'snickers chocolate bar': 'snickers chocolate bar',
    'snickers crisper chocolate bar': 'snickers crisper chocolate bar',
    'snickers peanut butter squared bars': 'snickers peanut butter squared bars',
    'sour patch blue raspberry candy': 'sour patch blue raspberry candy',
    'sour patch extreme soft chewy candy': 'sour patch extreme soft chewy candy',
    'sour patch kids candy': 'sour patch kids candy',
    'sour patch kids tropical candy': 'sour patch kids tropical candy',
    'sour patch strawberry candy': 'sour patch strawberry candy',
    'sour patch watermelon 86': 'sour patch watermelon 86',
    'sour punch real rainbow straws': 'sour punch real rainbow straws',
    'starburst favereds fruit chews': 'starburst favereds fruit chews',
    'starburst favereds minis fruit chews candy bag': 'starburst favereds minis fruit chews candy bag',
    'starburst original 85': 'starburst original 85',
    'starburst original fruit chews 89': 'starburst original fruit chews 89',
    'starburst original jelly beans': 'starburst original jelly beans',
    'starburst original minis fruit chews candy bag': 'starburst original minis fruit chews candy bag',
    'starburst tropical fruit chews candy': 'starburst tropical fruit chews candy',
    'swedish fish red candy': 'swedish fish red candy',
    'swedish fish soft chewy candy original 4 oz pack of 12': 'swedish fish soft chewy candy original 4 oz pack of 12',
    'sweetarts chewy sours 44': 'sweetarts chewy sours 44',
    'the original lemonhead': 'the original lemonhead',
    'toblerone swiss milk chocolate with honey and almond nougat 141 ounce bars pack of 4': 'toblerone swiss milk chocolate with honey and almond nougat 141 ounce bars pack of 4',
    'tootsie caramel apple pops': 'tootsie caramel apple pops',
    'trident gum': 'trident gum',
    'trolli sour brite crawlers': 'trolli sour brite crawlers',
    'trolli sour brite eggs candy': 'trolli sour brite eggs candy',
    'twix': 'twix',
    'twix bites': 'twix bites',
    'twizzlers bites cherry gummy candy': 'twizzlers bites cherry gummy candy',
    'twizzlers pull n peel candy cherry': 'twizzlers pull n peel candy cherry',
    'twizzlers twists strawberry': 'twizzlers twists strawberry',
    'warheads extreme sour hard candy': 'warheads extreme sour hard candy',
    'werthers original caramel hard candies': 'werthers original caramel hard candies',
    'york peppermint patty': 'york peppermint patty'
}
